enum BreweriesActionsType {
    REQUEST_SEARCH_BY_KEYWORD = 'BREWERIES/REQUEST_SEARCH_BY_KEYWORD',
    REQUEST_FILTER_BREWERIES = 'BREWERIES/REQUEST_FILTER_BREWERIES',

    REDUCER_FILTER_BREWERIES_SUCCESS = 'BREWERIES/REDUCER_FILTER_BREWERIES_SUCCESS',
    REDUCER_FILTER_BREWERIES_ERROR = 'BREWERIES/REDUCER_FILTER_BREWERIES_ERROR',
    REDUCER_SEARCH_BY_KEYWORD_SUCCESS = 'BREWERIES/REDUCER_SEARCH_BY_KEYWORD_SUCCESS',
    REDUCER_SEARCH_BY_KEYWORD_ERROR = 'BREWERIES/REDUCER_SEARCH_BY_KEYWORD_ERROR',
}

export default BreweriesActionsType;
